# Generated by Django 2.2 on 2020-05-14 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '用户账户', 'verbose_name_plural': '用户账户'},
        ),
    ]
