version: '3'

services:
  dyezweb:
    build:
      context: .
      dockerfile: _deployment/docker/django/Dockerfile
    image: dyezweb
    container_name: dyezweb
    working_dir: /project
    ports:
      - "8000:8000"
    volumes:
      - "./:/project"
    command: >
      sh -c "python manage.py wait_for_db &&
                python manage.py migrate &&
                python manage.py collectstatic --noinput &&
                gunicorn dyezweb.wsgi:application -w 4 -k gthread -b 0.0.0.0:8000 --chdir=/project"
    environment:
      - DB_HOST=postgres_db
      - DB_NAME=dyezweb
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=dyezweb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: .
      dockerfile: _deployment/docker/nginx/Dockerfile
    image: dyezweb_nginx
    container_name: dyezweb_nginx
    volumes:
      - ./static:/project/static
    ports:
      - "80:80"
      - "443:443"