version: '3'

services:
  dyezweb:
    build:
      context: .
      dockerfile: _deployment/docker/local/django/Dockerfile
    image: dyezweb
    container_name: dyezweb
    working_dir: /projects/dyezweb
    ports:
      - "8000:8000"
    volumes:
      - "./:/projects/dyezweb"
    command: >
      sh -c "python manage.py wait_for_db &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=postgres_db
      - DB_NAME=dyezweb
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=dyezweb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres