# Generated by Django 2.2.12 on 2020-05-26 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dorms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeCompetitionRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='三项竞赛评分细则名称')),
                ('code', models.CharField(blank=True, max_length=6, null=True, verbose_name='三项竞赛评分细则代码')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='三项竞赛评分细则描述')),
                ('min', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='评分区间下限')),
                ('max', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='评分区间上限')),
            ],
            options={
                'verbose_name': '三项竞赛评分细则',
                'verbose_name_plural': '三项竞赛评分细则',
                'db_table': 'tb_three_competition_rule',
            },
        ),
        migrations.CreateModel(
            name='ThreeCompetitionRuleOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='选项名称')),
                ('value', models.CharField(max_length=50, verbose_name='选项值')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='three_competitions.ThreeCompetitionRule', verbose_name='三项竞赛评分细则')),
            ],
            options={
                'verbose_name': '三项竞赛评分细则选项',
                'verbose_name_plural': '三项竞赛评分细则选项',
                'db_table': 'tb_three_competition_rule_option',
            },
        ),
        migrations.CreateModel(
            name='ThreeCompetitionRuleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='三项竞赛评分细则类别')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='类别描述')),
                ('category_type', models.SmallIntegerField(choices=[(1, '一级类别'), (2, '二级类别')], default=2, verbose_name='类别级别')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='three_competitions.ThreeCompetitionRuleCategory', verbose_name='父类别')),
            ],
            options={
                'verbose_name': '三项竞赛评分细则类别',
                'verbose_name_plural': '三项竞赛评分细则类别',
                'db_table': 'tb_three_competition_rule_category',
            },
        ),
        migrations.AddField(
            model_name='threecompetitionrule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='three_competitions.ThreeCompetitionRuleCategory', verbose_name='三项竞赛评分细则类别'),
        ),
        migrations.CreateModel(
            name='ThreeCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='评分')),
                ('is_minus', models.BooleanField(default=True, verbose_name='是否扣分')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='three_competitions.ThreeCompetitionRuleOption', verbose_name='三项竞赛评分细则选项')),
            ],
            options={
                'verbose_name': '三项竞赛',
                'verbose_name_plural': '三项竞赛',
                'db_table': 'tb_three_competition',
            },
        ),
        migrations.CreateModel(
            name='DormitoryCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='评分')),
                ('is_minus', models.BooleanField(default=True, verbose_name='是否扣分')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorms.Dormitory', verbose_name='寝室')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='three_competitions.ThreeCompetitionRuleOption', verbose_name='三项竞赛评分细则选项')),
            ],
            options={
                'verbose_name': '寝室竞赛',
                'verbose_name_plural': '寝室竞赛',
                'db_table': 'tb_three_competition_dormitory',
            },
        ),
    ]
