# Generated by Django 2.2 on 2020-05-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_competitions', '0002_auto_20200524_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threecompetitionrule',
            name='max',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='评分区间上限'),
        ),
        migrations.AlterField(
            model_name='threecompetitionrule',
            name='min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='评分区间下限'),
        ),
    ]
