# Generated by Django 2.2 on 2020-05-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_competitions', '0003_auto_20200524_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threecompetition',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='评分'),
        ),
    ]
