# Generated by Django 2.2 on 2020-05-24 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0001_initial'),
        ('three_competitions', '0004_auto_20200524_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='评分')),
                ('is_minus', models.BooleanField(default=True, verbose_name='是否扣分')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorms.Dormitory', verbose_name='寝室')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='three_competitions.ThreeCompetitionRuleOption', verbose_name='三项竞赛评分细则选项')),
            ],
            options={
                'verbose_name': '寝室竞赛',
                'verbose_name_plural': '寝室竞赛',
                'db_table': 'tb_three_competition_dormitory',
            },
        ),
    ]
