# Generated by Django 2.2 on 2020-05-14 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='title',
        ),
        migrations.AddField(
            model_name='major',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='专业代码'),
        ),
        migrations.AddField(
            model_name='major',
            name='name',
            field=models.CharField(default='admin', max_length=50, verbose_name='专业名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='major',
            name='quota',
            field=models.IntegerField(default=35, verbose_name='招生人数'),
        ),
        migrations.AddField(
            model_name='major',
            name='short_code',
            field=models.CharField(default='A', max_length=2, verbose_name='专业编号'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MajorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='专业类别')),
                ('desc', models.TextField(default='', verbose_name='类别描述')),
                ('category_type', models.SmallIntegerField(choices=[(1, '一级类别'), (2, '二级类别')], default=2, verbose_name='类别级别')),
                ('is_tab', models.BooleanField(default=False, help_text='是否导航', verbose_name='是否导航')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='majors.MajorCategory', verbose_name='父类别')),
            ],
            options={
                'verbose_name': '专业类别',
                'verbose_name_plural': '专业类别',
                'db_table': 'tb_major_category',
            },
        ),
        migrations.AddField(
            model_name='major',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='majors.MajorCategory', verbose_name='专业类别'),
            preserve_default=False,
        ),
    ]
