# Generated by Django 2.2.12 on 2020-05-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200527_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_active',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='姓名'),
        ),
    ]
