# Generated by Django 2.2.12 on 2020-05-28 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200528_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
    ]
