# Generated by Django 2.2 on 2020-05-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('short_code', models.CharField(max_length=3, verbose_name='寝室编号')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='寝室名称')),
                ('beds', models.SmallIntegerField(default=10, verbose_name='床位数')),
                ('with_bathroom', models.BooleanField(default=True, verbose_name='是否带卫生间')),
                ('building', models.SmallIntegerField(choices=[(6, '6号楼'), (7, '7号楼'), (8, '8号楼')], default=7, verbose_name='所属楼栋')),
            ],
            options={
                'verbose_name': '寝室',
                'verbose_name_plural': '寝室',
                'db_table': 'tb_dormitory',
            },
        ),
    ]
