version: '3'

services:
  dyezweb:
    build:
      context: .
      dockerfile: _deployment/docker/local/django/Dockerfile
    image: dyezweb
    container_name: dyezweb
    working_dir: /projects/dyezweb
    ports:
      - "8000:8000"
    command: /projects/dyezweb/_deployment/docker/local/django/start.sh