# Generated by Django 2.2 on 2020-05-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('sex', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('hukou', models.SmallIntegerField(choices=[(0, '农'), (1, '非农')], default=0, verbose_name='户口性质')),
                ('nationality', models.SmallIntegerField(choices=[(0, '汉族'), (1, '蒙古族'), (2, '回族'), (3, '藏族'), (4, '维吾尔族'), (5, '苗族'), (6, '彝族'), (7, '壮族'), (8, '布依族'), (9, '朝鲜族'), (10, '满族'), (11, '侗族'), (12, '瑶族'), (13, '白族'), (14, '土家族'), (15, '哈尼族'), (16, '哈萨克族'), (17, '傣族'), (18, '黎族'), (19, '僳僳族'), (20, '佤族'), (21, '畲族'), (22, '高山族'), (23, '拉祜族'), (24, '水族'), (25, '东乡族'), (26, '纳西族'), (27, '景颇族'), (28, '柯尔克孜族'), (29, '土族'), (30, '达斡尔族'), (31, '仫佬族'), (32, '羌族'), (33, '布朗族'), (34, '撒拉族'), (35, '毛南族'), (36, '仡佬族'), (37, '锡伯族'), (38, '阿昌族'), (39, '普米族'), (40, '塔吉克族'), (41, '怒族'), (42, '乌孜别克族'), (43, '俄罗斯族'), (44, '鄂温克族'), (45, '德昂族'), (46, '保安族'), (47, '裕固族'), (48, '京族'), (49, '塔塔尔族'), (50, '独龙族'), (51, '鄂伦春族'), (52, '赫哲族'), (53, '门巴族'), (54, '珞巴族'), (55, '基诺族')], default=0, verbose_name='民族')),
                ('native_place', models.CharField(blank=True, default='浙江东阳', max_length=50, verbose_name='籍贯')),
                ('id_card_no', models.CharField(max_length=18, verbose_name='身份证号码')),
                ('political_status', models.SmallIntegerField(choices=[(0, '群众'), (1, '团员')], default=0, verbose_name='政治面貌')),
                ('health_status', models.SmallIntegerField(choices=[(0, '健康或良好'), (1, '一般或较弱')], default=0, verbose_name='健康状况')),
                ('origin', models.SmallIntegerField(choices=[(0, '应届'), (1, '往届')], default=0, verbose_name='学生来源')),
                ('parent_name', models.CharField(max_length=50, verbose_name='家长姓名')),
                ('graduate_school', models.SmallIntegerField(choices=[(0, '安恬初中'), (1, '八达中小学'), (2, '春蕾学校'), (3, '大联初级中学\u3000'), (4, '东江镇中'), (5, '东阳市横店第二初级中学'), (6, '东阳市横店第三初级中学\u3000'), (7, '东阳市横店镇爱心学校'), (8, '防军初级中学'), (9, '歌山一中'), (10, '郭宅初中'), (11, '横店镇第一初级中学'), (12, '湖溪镇中'), (13, '虎鹿镇初级中学'), (14, '画水镇初级中学'), (15, '画溪初中'), (16, '怀鲁初中'), (17, '槐堂初中'), (18, '李宅初中'), (19, '六石街道初级中学'), (20, '马宅初中'), (21, '南马镇初级中学'), (22, '南溪初级中学'), (23, '千祥初级中学'), (24, '三单初中'), (25, '三联初中'), (26, '上村初级中学'), (27, '上卢初中'), (28, '唐表初中'), (29, '塘西初中'), (30, '亭塘初中'), (31, '巍山镇中'), (32, '吴宁二中'), (33, '吴宁三中'), (34, '吴宁四中'), (35, '吴宁一中'), (36, '象岗初中'), (37, '樟村初中'), (38, '佐村镇中')], default=0, verbose_name='初中毕业学校')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='担任职务')),
                ('major11', models.CharField(blank=True, max_length=50, null=True, verbose_name='大专班1')),
                ('major12', models.CharField(blank=True, max_length=50, null=True, verbose_name='大专班2')),
                ('major21', models.CharField(blank=True, max_length=50, null=True, verbose_name='中职班1')),
                ('major22', models.CharField(blank=True, max_length=50, null=True, verbose_name='中职班2')),
                ('filler_id', models.IntegerField(default=0, verbose_name='填报人')),
                ('adviser', models.CharField(blank=True, max_length=50, null=True, verbose_name='推荐人')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='家庭住址')),
                ('zip_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='邮编')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
                ('telephone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话号码')),
            ],
            options={
                'verbose_name': '入学申请（报名）',
                'verbose_name_plural': '入学申请（报名）',
                'db_table': 'tb_admission',
            },
        ),
    ]
