# Generated by Django 2.2 on 2020-05-14 00:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0002_auto_20200514_0825'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='filler_id',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='major11',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='major12',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='major21',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='major22',
        ),
        migrations.AddField(
            model_name='admission',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户账户'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='预报名确认状态'),
        ),
        migrations.AddField(
            model_name='admission',
            name='confirmed_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='admission',
            name='confirmed_on',
            field=models.DateField(blank=True, null=True, verbose_name='确认日期'),
        ),
        migrations.AddField(
            model_name='admission',
            name='confirmed_with',
            field=models.TextField(default='你已成功预报名，需网上报名时再次确认，优先录取。', max_length=200, verbose_name='确认文书'),
        ),
        migrations.AddField(
            model_name='admission',
            name='filler',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='填表人'),
        ),
        migrations.AddField(
            model_name='admission',
            name='memo',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='id_card_no',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator('\\d{17}\\w{1}', message='请输入正确格式的身份证号码！')], verbose_name='身份证号码'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('1[345678]\\d{9}', message='请输入正确格式的手机号码！')], verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('\\d{6}', message='请输入正确格式的邮政编码！')], verbose_name='邮编'),
        ),
        migrations.CreateModel(
            name='AdmissionMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='admissions.Admission', verbose_name='入学申请')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='majors.Major', verbose_name='专业')),
            ],
            options={
                'verbose_name': '入学申请专业',
                'verbose_name_plural': '入学申请专业',
                'db_table': 'tb_admissions_majors',
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='majors',
            field=models.ManyToManyField(through='admissions.AdmissionMajor', to='majors.Major', verbose_name='专业'),
        ),
    ]
