apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\yhb\Downloads\kompose-windows-amd64.exe convert -f D:\PycharmProjects\dyezweb\docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: dyezweb
  name: dyezweb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dyezweb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\yhb\Downloads\kompose-windows-amd64.exe convert -f D:\PycharmProjects\dyezweb\docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: dyezweb
    spec:
      containers:
      - args:
        - sh
        - -c
        - |-
          python manage.py wait_for_db &&
                    python manage.py migrate &&
                    python manage.py collectstatic --noinput &&
                    gunicorn dyezweb.wsgi:application -w 4 -k gthread -b 0.0.0.0:8000 --chdir=/project
        env:
        - name: DB_HOST
          value: postgres_db
        - name: DB_NAME
          value: dyezweb
        - name: DB_PASS
          value: postgres
        - name: DB_USER
          value: postgres
        image: dyezweb
        imagePullPolicy: ""
        name: dyezweb
        ports:
        - containerPort: 8000
        resources: {}
        workingDir: /project
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
