apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\yhb\Downloads\kompose-windows-amd64.exe convert -f D:\PycharmProjects\dyezweb\docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: dyezweb
  name: dyezweb
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    io.kompose.service: dyezweb
status:
  loadBalancer: {}
