# Generated by Django 2.2 on 2020-05-14 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '行政区划', 'verbose_name_plural': '行政区划'},
        ),
    ]
